vsync = true;
backend = "glx";
use-experimental-backends = true;

frame-opacity = 0.75;
corner-radius = 12;

#fading = false;
#fade-in-step = 0.03;
#fade-out-step = 0.03;
#fade-delta = 10;

blur-background-frame = true;

blur:
{
  method = "dual_kawase";
  strength = 12;
  background = true;
  background-frame = true;
  background-fixed = false;
  kern = "2x2box";
};

shadow = true;
shadow-radius = 14;
shadow-opacity = 0.45;
shadow-offset-x = -15;
shadow-offset-y = -5;

###################
# Animations
###################
 animations = (
    {
        triggers = [ "open" ];
        preset = "appear";
        duration = 0.35;
        curve = "cubic-bezier(0.22,0.61,0.36,1)";

    },
    {
        triggers = [ "close" ];
        preset = "disappear";
        duration = 0.25;
        curve = "cubic-bezier(0.22,0.61,0.36,1)";
    },
    {
        triggers = [ "hide" ];
        preset = "fly-out";
        direction = "down";
        duration = 0.35;
    },
    {
        triggers = [ "size" ];
        preset = "geometry-change";
        duration = 0.25;    
        curve = "cubic-bezier(0.08,0.82,0.17,1)";
    }
 )

rules = (
    {
        match = "name = 'Azura Desktop' || name = 'Tabazu'";
        blur-background = false;
        shadow = false;
        corner-radius = 0;
        animations = (
            {
                triggers = [ "open" ];
                preset = "appear";
                duration = 0.01; 
            }
        )
    },
    {
        match = "class_g = 'kitty'";
        opacity = 0.73;
    },
    {
        match = "fullscreen";
        corner-radius = 0;
    },
    {
        match = "window_type *= 'menu'";
        animations = (
            {
                triggers = [ "open", "show" ];
                preset = "slide-in";
                direction = "up";
                duration = 0.25;
            },
            {   triggers = [ "close", "hide" ];
                preset = "slide-out";
                direction = "up";
                duration = 0.35
            }
        )
    }
)
